print("Hello World")
# As we use python to run a file while we use python3 to run a file if we are a mac or linux user

print('hello world')

#String- Collection of Characters inside "Double quotes" os 'Single quotes'

# You can use 'Single quotes' inside "Double quotes" OR "Doubles quotes" inside 'Single quotes'

print("Hello 'world' world")
print('hello "world" world')

# But we can n't use quotes inside same quotes. Its give syntax error.
# eg. print("hello "world" world")

print("I'm PC")

# But print('I'm PC') gives error.